# Generated by Django 5.2.3 on 2025-07-13 14:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
